### ISSUE TITLE
Unable to load DLL unless absolute path is given

### ISSUE THREAD

**Issue by ZILtoid1991** [BindBC/bindbc-loader#2]
This caused some trouble while testing bindbc-zstandard if it loads the DLL, and bindbc-sdl is unable to find an SDL2.DLL file in the same directory as the application's EXE file.

I don't know if it's unique to my copy of Windows 10 or not.

**Comment by ZILtoid1991** [comment]
It seems not even the absolute path method is working...

**Comment by mdparker** [comment]
The loader uses the Win32 API function `LoadLibrary` to load DLLs. If the DLL is not on the system search path, it won't be loaded. So that part is working as intended. [This MSDN article](https://docs.microsoft.com/en-us/windows/desktop/Dlls/dynamic-link-library-search-order) describes the search path.

The load function allows you to specify paths for those cases when you do want to distribute an app with the DLL in a subdirectory. In that case, you need to make sure that you are using the correct path. When you say "the absolute path method" isn't working, are you actually using an absolute path ("C:/myapp/foo/bar") or a relative path ("foo/bar")? And what is the message you are seeing reported from the exception that's thrown?

**Comment by ZILtoid1991** [comment]
It was an architecture mismatch.

I think returning an error code different than noLibrary would be useful in this case.

**Comment by mdparker** [comment]
There's no system error code that would tell me that, but the system error messages do and knowing that at runtime generally isn't going to help you anyway. That's why I provide a means to get at the system error messages through the error handling functions (the loader does not throw exceptions so it can remain compatible with `-betterC` and `@nogc`). There's an example in the README showing how to do that.
