### ISSUE TITLE
Error information

### ISSUE THREAD

**Issue by o3o** [BindBC/bindbc-loader#6]
I'm stuck... I use [bindbc-raylib](https://github.com/o3o/bindbc-raylib):
```D
   RaylibSupport ret = loadRaylib();
   if (ret != raylibSupport) {
      errorf("raylib ret %s", ret);
      foreach(info; loader.errors) {
         error(info.error, ":", info.message);
      }
     ....
```

and I get error:
```
2020-10-13T17:48:42.335 [error] app.d:48:main raylib ret badLibrary
2020-10-13T17:48:42.335 [error] app.d:51:main 7EB87780:7EB877A0
2020-10-13T17:48:42.335 [error] app.d:51:main 7EB87780:7EB877A0
```
how do I know which function the symbol 7EB877A0 corresponds to?

Thank you very much

**Comment by mdparker** [comment]
Looks like you're printing pointer values. What is the implementation of your `error` function?

**Comment by o3o** [comment]
Thanks for your quick reply...
`error` is just a [experimental logger](https://dlang.org/phobos/std_experimental_logger.html) method

**Comment by mdparker** [comment]
I see. So `info.error` and `info.message` are of type `char*`. It seems the logger functions don't take any special steps for `char*` and just print the pointer value. You'll need to convert them to strings when passing them to the logger functions. Since they aren't going to change, you can use `std.string.fromStringz` to do so and no memory will be allocated.

```d
import std.string : fromStringz;
error(fromStringz(info.error), ":", fromStringz(info.message));
```

**Comment by o3o** [comment]
You are right (as usual).
I thought the problem was in your code ... fatal mistake :)

Thank you very much,
Greetings from Italy
